# Generated by Django 2.2.7 on 2019-11-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imgage',
            new_name='image',
        ),
    ]
